
lab50:
  files:
    - !exclude "*"
    - !include linear.c
    - !include maxsearch.c

check50:
  files: &check50_files
    - !exclude "*"
    - !include "*.c"
    
submit50:
  files: *check50_files
