lab50:
  files:
    - !exclude "*"
    - !include array.c
    - !include string.c

check50:
  files: &check50_files
    - !exclude "*"
    - !include "*.c"
    - !include "*.txt"
    - !include "*.doc"
    - !include "*.docx"
    - !include "*.pdf"

submit50:
  files: *check50_files
