lab50:
  files:
    - !exclude "*"
    - !include magic.c

check50:
  files: &check50_files
    - !exclude "*"
    - !include "*.c"
    - !include "*.txt"
    - !include "*.doc"
    - !include "*.docx"
    - !include "*.pdf"

submit50:
  files: 
    - !include "*.c"
